### ISSUE TITLE
Add initial support for arguments

### ISSUE THREAD

**Issue by jajuojan** [jajuojan/rs-license-formatter#6]
Add flags for current features:
- [x] Write TOC, license-texts or both (#9)
- [ ] "Join" licenses with similar texts (#5)
- [x] Guess the license-holder from license-text (MIT)
- [x] Fail or pass on missing licenses (#8)
- [x] Support passing package-links (#7)
